### ISSUE TITLE
Laser instances

### ISSUE THREAD

**Issue by JacobGilger** [JacobGilger/Collision-Course#1]
I need help figuring out how to make the program call a new instance of the drawLaser function each time the space bar is pressed. I'm kind of stuck on what to do from here. 
````
function drawLaser() {
	ctx.beginPath();
	ctx.moveTo(turretX+turretSize/2, laserY);
	ctx.lineTo(turretX+turretSize/2, laserY-laserSize);
	ctx.strokeStyle="#f00";
	ctx.stroke();
	ctx.closePath();
}

else if(spacePressed) {
	if(laserY<=laserSize) {

	}
	else{
		drawLaser();
		laserY-=laserdY;
	}
}`
```

**Comment by JacobGilger** [comment]
I think I solved this problem in the latest commit except I made it only be able to shoot once the laser hits the top

**Comment by cosinekitty** [comment]
Hi Jacob,

I will take a look at it this afternoon. 

Don

**Comment by JacobGilger** [comment]
I was able to fix the problem using an array and then used a timeout to make the user have to wait between shots.
