### ISSUE TITLE
Meteor array

### ISSUE THREAD

**Issue by JacobGilger** [JacobGilger/Collision-Course#2]
I know I have to use an array to make the meteors and use math.random to calculate the random x coordinate of where the metror will fall from but I’m not sure how to go about this

**Comment by cosinekitty** [comment]
First about the random number creation. Take a look at the function `getRandomInt` here:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random

Then you can use that helper function to create a random value for x. Be sure to note that the lower bound `min` is inclusive but the upper bound `max` is exclusive.  You can pick what range of x values you want to allow for the meteors.

I see you have global variables that can represent a single meteor: `meteorX` and `meteorY`. You can replace those variables with a single variable that represents an array of meteors:

````
var meteorList = [];
````

Now suppose you have randomly created a new meteor at coordinates (x1, y1). The syntax `{ x: x1, y: y1 }` creates an object with properties `x` and `y`.  For example:

````
meteorList.push({x: x1, y: y1});   // add another meteor to the list
console.log(meteorList[0].x);    // will print the first meteor's x coordinate to the console 
````

More realistically, you have a fixed value of `y1` and a random value of `x1`, so the code might look like:

````
meteorList.push( { x: getRandomInt(xmin, xmax), y: 0 } );
````

You can keep pushing more meteors to the list. That will allow there to be more than one meteor on the screen at one time.  If the meteor gets hit by a laser, you can remove it from the list using the array `splice` function:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice

For example, to delete the meteor at index `i`:
````
meteorList.splice(i, 1);
````

**Comment by TheOneWhoMade** [comment]
https://www.w3schools.com/code/tryit.asp?filename=FP63V53N4NEG

**Comment by TheOneWhoMade** [comment]
https://www.w3schools.com/code/tryit.asp?filename=FP63WJMMWABD
Meteors now repeatedly generate.

**Comment by TheOneWhoMade** [comment]
Do you think the laser should dissapear when it hits a meteor? if so, check this out: https://www.w3schools.com/code/tryit.asp?filename=FP64A9VYNLCG
